#!/bin/bash

if [ -z ${ADMINTOOL_SERVER} ] ; then
  ADMINTOOL_SERVER=127.0.0.1
fi

if [ -z ${ADMINTOOL_PORT} ] ; then
  ADMINTOOL_PORT=7080
fi

export BASE_SERVICE_URL=http://${ADMINTOOL_SERVER}:${ADMINTOOL_PORT}
